version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: sampleuser
  MYSQL_PASSWORD: samplepassword
  MYSQL_DATABASE: sampledb
  MYSQL_HOST_IP:
  REACT_APP_SERVER_PORT: 3001

services:
  server:
    build: ./server
    container_name: node_server_container
    environment:
      <<: *common-variables
    ports:
      - 3001:3001
    volumes:
      - ./server:/app
    command: npm start
  client:
    build: ./client
    container_name: client_container
    environment:
      <<: *common-variables
      NODE_PATH: src
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    links:
      - server
    command: npm start