version: "3.4"

services:
  server:
    container_name: server
    stdin_open: true
    build: 
      context: ./server
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    ports:
      - 3001:3001
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    command: npm run devStart

  client:
    container_name: client
    build: 
      context: ./client
    depends_on:
      - server
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    ports:
      - 3000:3000
    command: npm start
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      REACT_APP_API_HOST: 'localhost'
      REACT_APP_API_PORT: '3001'